//Generated by 24HRS
package Servlets;


import Models.Attendace;
import Controllers.AttendaceController;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet(name = "AttendaceServlet", urlPatterns = {"/AttendaceServlet"})


public class AttendaceServlet extends HttpServlet {

	protected void processRequest(HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException {
		response.setContentType("text/html;charset=UTF-8");
		try (PrintWriter out = response.getWriter()) {

		String action = request.getParameter("action");
		String pattern = "yyyy/MM/dd";
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
		String current_date = simpleDateFormat.format(new Date());

		if (action.equals("insert")) {
			int employee_id = Integer.parseInt(request.getParameter("employee_id"));
			String in_time = request.getParameter("in_time");
			String out_time = request.getParameter("out_time");
			Attendace obj = new Attendace();
			obj.setEmployee_id(employee_id);
			obj.setIn_time(in_time);
			obj.setOut_time(out_time);
			obj.setDate_time(current_date);
			try {
				AttendaceController.getInstance().Save(obj);
				response.getWriter().println("Saved!");
			} catch (Exception ex) {
				//error
			}
		} else if (action.equals("update")) {
			int attendance_id = Integer.parseInt(request.getParameter("attendance_id"));
			int employee_id = Integer.parseInt(request.getParameter("employee_id"));
			String in_time = request.getParameter("in_time");
			String out_time = request.getParameter("out_time");
			Attendace obj = new Attendace();
			obj.setAttendance_id(attendance_id);
			obj.setEmployee_id(employee_id);
			obj.setIn_time(in_time);
			obj.setOut_time(out_time);
			obj.setDate_time(current_date);
			try {
				AttendaceController.getInstance().Update(obj);
				response.getWriter().println("Updated!");
			} catch (Exception ex) {
				//error
			}

		} else if (action.equals("delete")) {
			int attendance_id = Integer.parseInt(request.getParameter("attendance_id"));
			Attendace obj = new Attendace();
			obj.setAttendance_id(attendance_id);
			try {
				AttendaceController.getInstance().Delete(obj);
				response.getWriter().println("Updated!");
			} catch (Exception ex) {
				//error
			}
		} else if (action.equals("serch")) {
			try {
				List<Attendace> list = new ArrayList<>();
				List stringList = new ArrayList<>();

				list = AttendaceController.getInstance().SearchAll();
				for (int i = 0; i < list.size(); i++) {
					String s = list.get(i).getAttendance_id() + "_"+list.get(i).getEmployee_id() + "_"+list.get(i).getIn_time() + "_"+list.get(i).getOut_time() + "_"+list.get(i).getDate_time() + "_";
					stringList.add(s);
				}
			String b = String.join("~", stringList);
			response.getWriter().println(b);
			} catch (Exception ex) {
				//Error
			}

		}
		}
	}

@Override
protected void doGet(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
		processRequest(request, response);
}

@Override
protected void doPost(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
		processRequest(request, response);
}

@Override
public String getServletInfo() {
	return "Short description";
}
}