//Generated by 24HRS
package Controllers;

import Models.Attendace;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class AttendaceController {

    Connector con = Connector.getInstance();

    private AttendaceController() {
    }

    private static final AttendaceController obj = new AttendaceController();

    public static AttendaceController getInstance() {
        return obj;
    }

    public void Save(Attendace data) throws Exception {
        con.getConnection();
        con.aud("INSERT INTO attendace(employee_id,in_time,out_time,date_time) values ('" + data.getEmployee_id() + "','" + data.getIn_time() + "','" + data.getOut_time() + "','" + data.getDate_time() + "') ");
    }

    public void Update(Attendace data) throws Exception {
        con.getConnection();
        con.aud("UPDATE attendace SET employee_id  = '" + data.getEmployee_id() + "',in_time  = '" + data.getIn_time() + "',out_time  = '" + data.getOut_time() + "' WHERE attendance_id = '" + data.getAttendance_id() + "'");
    }

    public void Delete(Attendace data) throws Exception {
        con.getConnection();
        con.aud("DELETE FROM attendace WHERE attendance_id = '" + data.getAttendance_id() + "'");
    }

    public List<Attendace> SearchAll() throws Exception {
        List<Attendace> objList = new ArrayList<Attendace>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM attendace");
        while (rset.next()) {
            Attendace obj = new Attendace();
            obj.setAttendance_id(rset.getInt(1));
            obj.setEmployee_id(rset.getInt(2));
            obj.setIn_time(rset.getString(3));
            obj.setOut_time(rset.getString(4));
            obj.setDate_time(rset.getString(5));
            objList.add(obj);
        }

        return objList;
    }

    public List<Attendace> Search(Attendace data) throws Exception {
        List<Attendace> objList = new ArrayList<Attendace>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM attendace WHERE attendance_id = '" + data.getAttendance_id() + "'");
        while (rset.next()) {
            Attendace obj = new Attendace();
            obj.setAttendance_id(rset.getInt(1));
            obj.setEmployee_id(rset.getInt(2));
            obj.setIn_time(rset.getString(3));
            obj.setOut_time(rset.getString(4));
            obj.setDate_time(rset.getString(5));
            objList.add(obj);
        }

        return objList;
    }

    public List<Attendace> getAttendanceMonth(int employeeId, String year, String month) throws Exception {
        String keyDate = year + "/" + month + "%";
        List<Attendace> objList = new ArrayList<Attendace>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM attendace WHERE date_time LIKE '" + keyDate + "' AND employee_id = '" + employeeId + "'");
        while (rset.next()) {
            Attendace obj = new Attendace();
            obj.setAttendance_id(rset.getInt(1));
            obj.setEmployee_id(rset.getInt(2));
            obj.setIn_time(rset.getString(3));
            obj.setOut_time(rset.getString(4));
            obj.setDate_time(rset.getString(5));
            objList.add(obj);
        }

        return objList;
    }

}
